[package]
name = "noodles-squab"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
anyhow = "1.0.32"
clap = "2.32.0"
flate2 = "1.0.14"
futures = { version = "0.3.17", default-features = false, features = ["std"] }
git-testament = "0.2.0"
interval-tree = { git = "https://github.com/zaeleus/interval-tree.git", rev = "e303d7254d53de5c418d6079d4b66c30c10958d4" }
noodles = { version = "0.11.0", features = ["bam", "gff", "sam"] }
noodles-bam = { version = "0.7.0", features = ["async"] }
num_cpus = "1.12.0"
tokio = { version = "1.0.1", features = ["fs", "rt-multi-thread"] }
tracing = "0.1.25"
tracing-subscriber = "0.2.16"

[dev-dependencies]
tokio = { version = "1.0.1", features = ["macros"] }
