[package]
name = "squab"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.59.0"
publish = false

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
anyhow = "1.0.32"
clap = { version = "4.0.4", features = ["cargo", "string"] }
flate2 = "1.0.14"
futures = { version = "0.3.17", default-features = false, features = ["std"] }
git-testament = "0.2.0"
interval-tree = { git = "https://github.com/zaeleus/interval-tree.git", rev = "e303d7254d53de5c418d6079d4b66c30c10958d4" }
mimalloc = { version = "0.1.26", default-features = false }
noodles = { version = "0.27.0", features = ["bam", "core", "gff", "sam"] }
noodles-bam = { version = "0.22.0", features = ["async"] }
noodles-bgzf = { version = "0.15.0", features = ["libdeflate"] }
tokio = { version = "1.0.1", features = ["fs", "rt-multi-thread"] }
tracing = "0.1.25"
tracing-subscriber = "0.3.3"

[dev-dependencies]
tokio = { version = "1.0.1", features = ["macros"] }
