[package]
name = "noodles-count-features"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
clap = "2.32.0"
csv = "1.0.5"
env_logger = "0.7.1"
git-testament = "0.1.6"
interval-tree = { git = "https://github.com/zaeleus/interval-tree.git", rev = "2a0bab09e79766f3daf8b02725f27f66dbd9d009" }
log = "0.4.5"
noodles = { git = "https://github.com/zaeleus/noodles.git", rev = "29afcb400370b3f2124794a43c119b5a8ee3acd3" }
