[package]
name = "noodles-squab"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
clap = "2.32.0"
env_logger = "0.7.1"
flate2 = "1.0.14"
git-testament = "0.1.6"
interval-tree = { git = "https://github.com/zaeleus/interval-tree.git", rev = "e303d7254d53de5c418d6079d4b66c30c10958d4" }
log = "0.4.5"
noodles = { git = "https://github.com/zaeleus/noodles.git", rev = "a67149372f3dee9d43dd27d997425000e0f38a1f" }
noodles-bam = { git = "https://github.com/zaeleus/noodles.git", rev = "a67149372f3dee9d43dd27d997425000e0f38a1f" }
noodles-gff = { git = "https://github.com/zaeleus/noodles.git", rev = "a67149372f3dee9d43dd27d997425000e0f38a1f" }
noodles-sam = { git = "https://github.com/zaeleus/noodles.git", rev = "a67149372f3dee9d43dd27d997425000e0f38a1f" }
num_cpus = "1.12.0"
tokio = { version = "0.2.6", features = ["rt-threaded"] }
