[package]
name = "noodles-count-features"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"

[dependencies]
clap = "2.32.0"
env_logger = "0.5.13"
interval-tree = { git = "https://github.com/zaeleus/interval-tree.git" }
log = "0.4.5"
noodles = { git = "https://github.com/zaeleus/noodles.git" }
