[package]
name = "noodles-squab"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
clap = "2.32.0"
env_logger = "0.7.1"
git-testament = "0.1.6"
interval-tree = { git = "https://github.com/zaeleus/interval-tree.git", tag = "v0.2.0" }
log = "0.4.5"
noodles = { git = "https://github.com/zaeleus/noodles.git", rev = "27f8c25b937ebb50d5cd44f730385f33d69eb4b3" }
noodles-bam = { git = "https://github.com/zaeleus/noodles.git", rev = "27f8c25b937ebb50d5cd44f730385f33d69eb4b3" }
noodles-gff = { git = "https://github.com/zaeleus/noodles.git", rev = "27f8c25b937ebb50d5cd44f730385f33d69eb4b3" }
noodles-sam = { git = "https://github.com/zaeleus/noodles.git", rev = "27f8c25b937ebb50d5cd44f730385f33d69eb4b3" }
num_cpus = "1.12.0"
tokio = { version = "0.2.6", features = ["rt-threaded"] }
