[package]
name = "noodles-squab"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
clap = "2.32.0"
env_logger = "0.7.1"
git-testament = "0.1.6"
interval-tree = { git = "https://github.com/zaeleus/interval-tree.git", rev = "2a0bab09e79766f3daf8b02725f27f66dbd9d009" }
log = "0.4.5"
noodles = { git = "https://github.com/zaeleus/noodles.git", rev = "3f1d386f7349a8661145bcb958b0d6c4c55f2366" }
noodles-bam = { git = "https://github.com/zaeleus/noodles.git", rev = "3f1d386f7349a8661145bcb958b0d6c4c55f2366" }
noodles-gff = { git = "https://github.com/zaeleus/noodles.git", rev = "3f1d386f7349a8661145bcb958b0d6c4c55f2366" }
tokio = { version = "0.2.6", features = ["macros", "rt-threaded"] }
