[package]
name = "noodles-squab"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
anyhow = "1.0.32"
clap = "2.32.0"
env_logger = "0.8.1"
flate2 = "1.0.14"
git-testament = "0.1.6"
interval-tree = { git = "https://github.com/zaeleus/interval-tree.git", rev = "e303d7254d53de5c418d6079d4b66c30c10958d4" }
log = "0.4.5"
noodles = { git = "https://github.com/zaeleus/noodles.git", rev = "8204ecfc29da5d54634e12c198340d825b76d8e9" }
noodles-bam = { git = "https://github.com/zaeleus/noodles.git", rev = "8204ecfc29da5d54634e12c198340d825b76d8e9" }
noodles-gff = { git = "https://github.com/zaeleus/noodles.git", rev = "8204ecfc29da5d54634e12c198340d825b76d8e9" }
noodles-sam = { git = "https://github.com/zaeleus/noodles.git", rev = "8204ecfc29da5d54634e12c198340d825b76d8e9" }
num_cpus = "1.12.0"
tokio = { version = "0.3.0", features = ["rt-multi-thread"] }
